#!/usr/bin/env node

/**
 * git pre-commit hook文件运行此脚本
 */


var Path = require('path'),
	fs = require('fs'),
	exec = require('child_process').exec;


var files = [
	'README.md', 
	'package.json'
];


function autoConfig(file, o) {
	var path = Path.normalize(Path.join(__dirname, '..', file));
	fs.readFile(path, 'utf-8', function(e, body) {
		if (e) {
			throw e;
		}

		for (var k in o) {
			body = body.replace(k, o[k]);
		}

		fs.writeFile(path, body);
	});
}


exec('git describe', function(error, stdout, stderr) {
	var pattern = /v\d+\.\d+\.\d+-\d+/;
	var o = {};
	o[pattern] = pattern.exec(stdout)[0];

	files.forEach(function(file) {
		autoConfig(file, o);
	});

});
